name: Test workflow

on:
  workflow_call:

env:
  ImageOS: macos1240
  XCODE_CI_VERSION: 15.0.1
  DEFAULT_DEVICE_TYPE: iPhone-15
  DEFAULT_DEVICE_NAME: iPhone 15

jobs:
  on-success:
    runs-on: macos-latest
    steps:
      - run: echo 'The triggering workflow passed'