name: Test workflow

on:
  workflow_call:
  workflow_run:
    workflows: [Pull Request]
    types:
      - completed

env:
  ImageOS: macos1240
  XCODE_CI_VERSION: 15.0.1
  DEFAULT_DEVICE_TYPE: iPhone-15
  DEFAULT_DEVICE_NAME: iPhone 15

jobs:
  do-more:
    runs-on: macos-latest
    if:  ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
